# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vcontrol add-on
version: "1.0.0"
slug: vcontrold
description: Vcontrol add-on
url: "https://github.com/Alexandre-io/homeassistant-vcontrol"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
usb: true
ports:
  - 3002