# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vcontrol add-on
version: "1.0.2"
slug: vcontrold
description: Vcontrol add-on
url: "https://github.com/Alexandre-io/homeassistant-vcontrol"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  tty: "/dev/ttyUSB0"
schema:
  tty: "str?"
image: "alexandreio/{arch}-homeassistant-vcontrol"
usb: true
apparmor: false
services:
  - mqtt:need
devices:
  - /dev/ttyUSB0:/dev/ttyUSB0:rwm
  - /dev/ttyUSB1:/dev/ttyUSB1:rwm
  - /dev/ttyUSB2:/dev/ttyUSB2:rwm
  - /dev/ttyUSB3:/dev/ttyUSB3:rwm