# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vcontrol add-on
version: "1.0.2"
slug: vcontrold
description: Vcontrol add-on
url: "https://github.com/Alexandre-io/homeassistant-vcontrol"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
  - share:rw
options:
  tty: "/dev/ttyUSB0"
schema:
  tty: "str?"
image: "alexandreio/{arch}-homeassistant-vcontrol"
apparmor: false
kernel_modules: true
full_access: true
services:
  - mqtt:need